### PR TITLE
Refactors assessment

### PR DESCRIPTION
**Pull request by Genyus**
- Removes all predefined content and directs learners to create a new repo from scratch
- Closes https://codingblackfemales.atlassian.net/browse/TECH-601

### CODE REVIEW

**Review by tanyapowell — COMMENTED** [review]
I have a question regarding the student workflow - is the new expectation that students will only need to refer to the README for assessment criteria, without forking the repo?

**Comment by Genyus** [comment]
@tanyapowell That's correct, they'll now be expected to create their own repo rather than forking this one

**Comment by tanyapowell** [comment]
Is this better suited to be on the Learning Platform, so it's in the same place as the other assessment related content?

**Comment by Genyus** [comment]
Hm. Yeah, that makes sense, actually.

**Pull request merged**
